(() => {
  if (window.top !== window || document.getElementById("__chutty")) return;
  const KEYS = ["filechute-chatgpt-drag-source-v1", "filechute-google-drag-source-v1", "filechute-yandex-drag-source-v1"];
  let busy = false, timer;
  const host = document.createElement("div"); host.id = "__chutty";
  Object.assign(host.style, { all:"initial", position:"fixed", right:"18px", bottom:"18px", width:"92px", height:"105px", zIndex:"2147483647", pointerEvents:"auto" });
  const shadow = host.attachShadow({ mode:"closed" }); shadow.innerHTML = `<style>*{box-sizing:border-box}.c{position:absolute;inset:8px;padding:0;border:0;background:transparent;filter:drop-shadow(0 6px 6px #0004);cursor:copy;transition:.13s}.p{position:absolute;inset:8px 3px 2px;display:grid;place-content:center;justify-items:center;gap:3px;border:1px solid #d3b63f;border-radius:6px 6px 13px 13px;background:repeating-linear-gradient(#ffe87a 0 14px,#f8db61 15px);color:#4a3a13;font:900 18px system-ui}.m{position:absolute;left:13px;right:13px;top:8px;height:14px;border:3px solid #4b3a13;border-radius:50%;background:#241b0b}.l{font-size:10px;letter-spacing:.13em}.c.over{transform:scale(1.09) rotate(-2deg)}.c.over .m{height:21px}.c.ok{animation:happy .45s}.c.no{animation:no .35s}@keyframes happy{50%{transform:translateY(-8px) rotate(5deg)}}@keyframes no{25%,75%{transform:translateX(-4px)}50%{transform:translateX(4px)}}</style><button class="c" title="Drop an image into Chute" aria-label="Chutty: drop an image into Chute"><span class="m"></span><span class="p"><span class="f">•ᴗ•</span><span class="l">CHUTE</span></span></button>`;
  const chute = shadow.querySelector(".c"), face = shadow.querySelector(".f"), label = shadow.querySelector(".l");
  function feedback(ok, detail = "") { clearTimeout(timer); chute.className = `c ${ok ? "ok" : "no"}`; face.textContent = ok ? "^ᴗ^" : "×︵×"; label.textContent = ok ? "YUMMY" : "FAILED"; chute.title = detail || (ok ? "Saved in Chute" : "Chute could not save that image"); timer = setTimeout(() => { chute.className="c"; face.textContent = Math.random() < .015 ? "♥ᴗ♥" : "•ᴗ•"; label.textContent="CHUTE"; }, 950); }
  async function recentCapture() { const values = await chrome.storage.local.get(KEYS); return KEYS.map((key) => values[key]).filter((item) => item?.urls?.length).sort((a,b) => b.capturedAt-a.capturedAt)[0]; }
  function extension(type, url) { const known = {"image/jpeg":"jpg","image/png":"png","image/webp":"webp","image/gif":"gif","image/avif":"avif"}[type]; if (known) return known; return String(url).match(/\.([a-z0-9]{2,5})(?:[?#]|$)/i)?.[1] || "png"; }
  async function recover() { const capture = await recentCapture(); if (!capture || Date.now() - capture.capturedAt > 30000) throw new Error("Drag the image again, then drop it promptly on Chutty."); for (const url of capture.urls) { try { const response = await fetch(url, { credentials:"include" }); if (!response.ok) continue; const blob = await response.blob(); if (!blob.size || !blob.type.startsWith("image/")) continue; const base = String(capture.title || "image").replace(/\.[a-z0-9]+$/i, "").slice(0,80); return new File([blob], `${base}.${extension(blob.type,url)}`, { type:blob.type }); } catch {} } throw new Error("The site did not expose readable image bytes. Try dragging the downloaded image file."); }
  async function consume(event) { if (busy) return; busy=true; try { const dropped = [...(event.dataTransfer?.files || [])].find((file) => file.size); const file = dropped || await recover(); const result = await chrome.runtime.sendMessage({ type:"chute-store-file-v3", file }); if (!result?.ok) throw new Error(result?.error || "Write failed"); feedback(true, `Saved ${result.name} in Chute`); } catch(error) { feedback(false,error.message); } finally { busy=false; chute.classList.remove("over"); } }
  chute.ondragenter = chute.ondragover = (event) => { event.preventDefault(); event.stopPropagation(); chute.classList.add("over"); if (event.dataTransfer) event.dataTransfer.dropEffect="copy"; };
  chute.ondragleave = () => chute.classList.remove("over"); chute.ondrop = (event) => { event.preventDefault(); event.stopPropagation(); void consume(event); };
  const mount = () => { if (!host.isConnected && document.documentElement) document.documentElement.append(host); }; mount(); document.addEventListener("DOMContentLoaded",mount,{once:true});
})();
